# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_control_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: perfect_integration_vertical
# A relatively short label, used when rendering visualisations (required)
label: Perfect Integration Vertical
# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "Positive control method which imitates what perfect batch integration."
# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  The method actually just return the validation data but just changing the batch
  and sample ID to those that are in the unintegrated_censored.
  Because the marker expression is the exactly same as the validation data, there won't
  be any batch effect present.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: python_script
    path: script.py

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
