# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: cycombine_one_control_to_mid
# A relatively short label, used when rendering visualisations (required)
label: cyCombine (one-control, to-middle)
# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "cyCombine run with control sample from one group only, correcting to a midpoint"
description: |
  cyCombine perform batch integration using self-organizing maps and ComBat.
  It first uses self-organizing maps (SOM) to group similar cells into clusters, 
  then applies a ComBat-based method to correct batch effects within 
  each cluster. 
  Here, we run cyCombine using control samples only from one biological group (replicates, in cyCombine terms), 
  with a square SOM grid and correct the batches to a midpoint derived from all batches.
  The size of the SOM grid is varied linearly between value of 6-16, with default set to 8
  following the default value in create_som function in cyCombine.
  Rlen, which is the number of times data is presented to the SOM network and can impact
  clustering quality. 
  It is varied linearly between value of 10-20 with default set to 10.
references:
  doi: 
    - 10.1038/s41467-022-29383-5
links:
  documentation: https://biosurf.org/cyCombine.html
  repository: https://github.com/biosurf/cyCombine

argument_groups:
  - name: Parameters
    arguments:
      - type: integer
        name: --som_grid_size
        info:
          optimize:
            type: linear
            lower: 6
            upper: 16
        default: 8
        description: SOM grid size used by create_som
      - type: integer
        name: --rlen
        info:
          optimize:
            type: linear
            lower: 10
            upper: 20
        default: 10
        description: The number of time data is presented to SOM when clustering

resources:
  # The script of your component (required)
  - type: r_script
    path: script.R
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  - type: docker
    image: openproblems/base_r:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: r
        bioc: [sva]
        github: [biosurf/cyCombine]

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
