__merge__: ../../api/comp_method.yaml

name: limma_remove_batch_effect
label: Limma removeBatchEffect
summary: Uses a linear model and matrix decomposition to remove batch effects from a dataset
description: |
  Limma removeBatchEffect is a method that uses a linear model and matrix
  decomposition to remove batch effects from a dataset. It first fits a linear
  model to the data, then decomposes the model matrix into a set of orthogonal
  components. The batch effect is then removed by subtracting the component
  corresponding to the batch effect from the data.
references:
  doi: 
    - 10.1093/nar/gkv007
links:
  documentation: https://bioinf.wehi.edu.au/limma
  repository: https://github.com/bioc/limma

resources:
  - type: r_script
    path: script.R

engines:
  - type: docker
    image: openproblems/base_r:1
    setup:
      - type: r
        bioc: limma

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
