# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: cycombine_all_controls
# A relatively short label, used when rendering visualisations (required)
label: cyCombine with all controls
# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "cyCombine with all control samples"
description: |
  cyCombine perform batch integration using self-organizing maps and ComBat.
  It first uses self-organizing maps (SOM) to group similar cells into clusters, 
  then applies a ComBat-based method to correct batch effects within 
  each cluster. 
  Here, we run cyCombine with all control samples (replicates in cyCombine terminology)
  using square SOM grid.
  The size of the SOM grid is varied linearly between value of 6-12, with default set to 8.
  Rlen, which is the number of times data is presented to the SOM network is fixed to 
  the default 10 and not varied in parameter optimisation as we are not assessing how
  effective SOM is for clustering.
references:
  doi: 
    - 10.1038/s41467-022-29383-5
links:
  documentation: https://biosurf.org/cyCombine.html
  repository: https://github.com/biosurf/cyCombine

argument_groups:
  - name: Parameters
    arguments:
      - type: integer
        name: --som_grid_size
        info:
          optimize:
            type: linear
            lower: 6
            upper: 12
        default: 8
        description: SOM grid size used by create_som
      

resources:
  # The script of your component (required)
  - type: r_script
    path: script.R
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  - type: docker
    image: openproblems/base_r:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: r
        bioc: [sva]
        github: [biosurf/cyCombine]

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
