import sys

import anndata as ad
import numpy as np

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
    "input_unintegrated": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    "input_integrated_split1": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_split1.h5ad",
    "input_integrated_split2": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_split2.h5ad",
    "output": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_lisi.h5ad",
}
meta = {
    "name": "lisi",
    "resources_dir": "src/utils",
}
## VIASH END

sys.path.append(meta["resources_dir"])
import helper as lisi_helper
from helper_functions import (
    get_obs_var_for_integrated,
    remove_unlabelled,
    subset_markers_tocorrect,
    subset_nocontrols,
)

# TODO: no idea why the new anndata >= 0.11 needs this even if we don't write anything to obs?
ad.settings.allow_write_nullable_strings = True

print("Reading input files", flush=True)
input_unintegrated = ad.read_h5ad(par["input_unintegrated"])
input_integrated_split1 = ad.read_h5ad(par["input_integrated_split1"])
input_integrated_split2 = ad.read_h5ad(par["input_integrated_split2"])

print("Formatting input files", flush=True)
integrated_s1, integrated_s2 = get_obs_var_for_integrated(
    input_integrated_split1, input_integrated_split2, input_unintegrated
)
integrated_s1 = subset_markers_tocorrect(integrated_s1)
integrated_s1 = subset_nocontrols(integrated_s1)
integrated_s1 = remove_unlabelled(integrated_s1)

integrated_s2 = subset_markers_tocorrect(integrated_s2)
integrated_s2 = subset_nocontrols(integrated_s2)
integrated_s2 = remove_unlabelled(integrated_s2)

print("Compute metrics", flush=True)

# iLISI is computed globally (not per group) across all cells in each split.
# n_batches is taken from split 1; both splits share the same batch labels.
n_batches = len(integrated_s1.obs["batch"].unique())

print("Compute iLisi for split 1", flush=True)
ilisi_s1, ilisi_s1_per_cell = lisi_helper.compute_ilisi(integrated_s1, n_batches)

print("Compute iLisi for split 2", flush=True)
ilisi_s2, ilisi_s2_per_cell = lisi_helper.compute_ilisi(integrated_s2, n_batches)

ilisi = np.mean([ilisi_s1, ilisi_s2])

print("Compute cLisi for split 1", flush=True)
clisi_s1, clisi_s1_per_cell = lisi_helper.compute_clisi(integrated_s1)

print("Compute cLisi for split 2", flush=True)
clisi_s2, clisi_s2_per_cell = lisi_helper.compute_clisi(integrated_s2)

clisi = np.mean([clisi_s1, clisi_s2])

print(f"iLisi split 1: {ilisi_s1}", flush=True)
print(f"iLisi split 2: {ilisi_s2}", flush=True)
print(f"Mean iLisi: {ilisi}", flush=True)
print(f"cLisi split 1: {clisi_s1}", flush=True)
print(f"cLisi split 2: {clisi_s2}", flush=True)
print(f"Mean cLisi: {clisi}", flush=True)

print("Write output AnnData to file", flush=True)
# uns layout:
#   metric_ids / metric_values: iLISI and cLISI summary scores (mean across splits).
#   ilisi_per_split: per-split iLISI details — normalised score, raw per-cell values,
#     and the corresponding cell IDs.
#   clisi_per_split: same structure for cLISI.
uns = {
    "dataset_id": integrated_s1.uns["dataset_id"],
    "method_id": integrated_s1.uns["method_id"],
    "metric_ids": ["iLisi", "cLisi"],
    "metric_values": [ilisi, clisi],
    "ilisi_per_split": {
        "split_1": {
            "score": ilisi_s1,
            "per_cell": ilisi_s1_per_cell,
            "cell_ids": np.array(integrated_s1.obs_names),
        },
        "split_2": {
            "score": ilisi_s2,
            "per_cell": ilisi_s2_per_cell,
            "cell_ids": np.array(integrated_s2.obs_names),
        },
    },
    "clisi_per_split": {
        "split_1": {
            "score": clisi_s1,
            "per_cell": clisi_s1_per_cell,
            "cell_ids": np.array(integrated_s1.obs_names),
        },
        "split_2": {
            "score": clisi_s2,
            "per_cell": clisi_s2_per_cell,
            "cell_ids": np.array(integrated_s2.obs_names),
        },
    },
}

output = ad.AnnData(uns=uns)
output.write_h5ad(par["output"], compression="gzip")

print(f"Anndata written to {par['output']}", flush=True)
