import sys

import anndata as ad
import numpy as np

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
    "input_unintegrated": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    "input_integrated_split1": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_split1.h5ad",
    "input_integrated_split2": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_split2.h5ad",
    "output": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/output_lisi.h5ad",
}
meta = {
    "name": "lisi",
    "resources_dir": "src/utils",
}
## VIASH END

sys.path.append(meta["resources_dir"])
import helper as lisi_helper
from helper_functions import (
    get_obs_var_for_integrated,
    remove_unlabelled,
    subset_markers_tocorrect,
    subset_nocontrols,
)

# TODO: no idea why the new anndata >= 0.11 needs this even if we don't write anything to obs?
ad.settings.allow_write_nullable_strings = True

print("Reading input files", flush=True)
input_unintegrated = ad.read_h5ad(par["input_unintegrated"])
input_integrated_split1 = ad.read_h5ad(par["input_integrated_split1"])
input_integrated_split2 = ad.read_h5ad(par["input_integrated_split2"])

print("Formatting input files", flush=True)
integrated_s1, integrated_s2 = get_obs_var_for_integrated(
    input_integrated_split1, input_integrated_split2, input_unintegrated
)
integrated_s1 = subset_markers_tocorrect(integrated_s1)
integrated_s1 = subset_nocontrols(integrated_s1)
integrated_s1 = remove_unlabelled(integrated_s1)

integrated_s2 = subset_markers_tocorrect(integrated_s2)
integrated_s2 = subset_nocontrols(integrated_s2)
integrated_s2 = remove_unlabelled(integrated_s2)

print("Compute metrics", flush=True)
print("Compute iLisi per group for split 1", flush=True)
ilisi_s1_per_group, ilisi_s1_per_cell_per_group = lisi_helper.compute_ilisi_per_group(
    integrated_s1, "split 1"
)

print("Compute iLisi per group for split 2", flush=True)
ilisi_s2_per_group, ilisi_s2_per_cell_per_group = lisi_helper.compute_ilisi_per_group(
    integrated_s2, "split 2"
)

# Compute final iLISI as the mean across all groups from both splits.
# If all groups across both splits were skipped (batch confounded by group), return NaN.
all_ilisi_values = list(ilisi_s1_per_group.values()) + list(ilisi_s2_per_group.values())
ilisi = np.nanmean(all_ilisi_values) if len(all_ilisi_values) > 0 else np.nan

print("Compute cLisi for split 1", flush=True)
clisi_s1, clisi_s1_per_cell = lisi_helper.compute_clisi(integrated_s1)

print("Compute cLisi for split 2", flush=True)
clisi_s2, clisi_s2_per_cell = lisi_helper.compute_clisi(integrated_s2)

clisi = np.mean([clisi_s1, clisi_s2])

# Print all results to stdout for logging purposes.
for group, val in ilisi_s1_per_group.items():
    print(f"iLisi split 1 group {group}: {val}", flush=True)
    print(f"iLisi split 2 group {group}: {val}", flush=True)

print("cLisi split 1:", clisi_s1, flush=True)
print("cLisi split 2:", clisi_s2, flush=True)
print("Mean iLisi:", ilisi, flush=True)
print("Mean cLisi:", clisi, flush=True)

print("Write output AnnData to file", flush=True)
# uns layout:
#     iLisi = mean iLISI across all groups and both splits.
#     cLisi = mean cLISI across both splits.
#   ilisi_per_split: {split_1, split_2} -> {group: iLISI score}.
#     Groups where batch is fully confounded by group are skipped and absent.
#   ilisi_per_cell_per_split: same structure, but values are raw per-cell iLISI score
#   clisi_per_split: {split_1, split_2} -> cLISI score for that split.
#   clisi_per_cell_per_split: {split_1, split_2} -> raw per-cell cLISI score for that split.
uns = {
    "dataset_id": integrated_s1.uns["dataset_id"],
    "method_id": integrated_s1.uns["method_id"],
    "metric_ids": ["iLisi", "cLisi"],
    "metric_values": [ilisi, clisi],
    "ilisi_per_split": {
        "split_1": ilisi_s1_per_group,
        "split_2": ilisi_s2_per_group,
    },
    "ilisi_per_cell_per_split": {
        "split_1": ilisi_s1_per_cell_per_group,
        "split_2": ilisi_s2_per_cell_per_group,
    },
    "clisi_per_split": {
        "split_1": clisi_s1,
        "split_2": clisi_s2,
    },
    "clisi_per_cell_per_split": {
        "split_1": clisi_s1_per_cell,
        "split_2": clisi_s2_per_cell,
    },
}

output = ad.AnnData(uns=uns)
output.write_h5ad(par["output"], compression="gzip")

print(f"Anndata written to {par['output']}", flush=True)
