__merge__: ../../api/comp_data_processor.yaml
name: process_dataset

resources:
  - type: python_script
    path: script.py
  - path: /common/helper_functions/subset_h5ad_by_format.py

engines:
  - type: docker
    image: openproblems/base_python:1.0.0

runners:
  - type: executable
  - type: nextflow
    directives:
      label: [highmem, midcpu, midtime]