__merge__: /src/api/comp_control_method.yaml
name: shuffle_integration_globally
label: Shuffle Integration Globally
summary: Randomly shuffle cells in the whole dataset.
description: |
  This negative control randomly shuffles all cells in the input data.
  Cells lose all identity information (sample, batch, and cell type).
  
  Example: a cell from mouse 3 batch 1 may be reassigned to any sample in the data 
  (mouse 4 batch 1 or mouse 6 batch 2).
# status: disabled
resources:
  - type: python_script
    path: script.py
  - path: /src/control_methods/utils.py
engines:
  - type: docker
    image: openproblems/base_python:1
runners:
  - type: executable
  - type: nextflow
    directives:
      label: [lowtime,lowmem,lowcpu]
