
__merge__: ../../api/comp_metric.yaml

name: average_batch_r2

# Metadata for your component
info:
  metrics:
      # A unique identifier for your metric (required).
      # Can contain only lowercase letters or underscores.
    - name: average_batch_r2_global
      # A relatively short label, used when rendering visualisarions (required)
      label: Average Batch R-squared Global
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "The average batch R-squared quantifies, on average, how strongly the batch variable B explains the variance in the data."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        First, a simple linear model `sklearn.linear_model.LinearRegression` is fitted for each paired sample and marker to determine the fraction of variance (R^2) explained by the batch covariate B. |
        The average batch R_squared is then computed as the average of the $R^2$ values across all paired samples, markers. |
        As a result, $\overline{R^2_B}_{global}$ quantifies how much of the total variability in the data is driven by batch effects. Consequently, lower values are desirable. |

        $\overline{R^2_B}_{global} = \frac{1}{N*M}\sum_{\substack{(x_{\mathrm{int}},\,x_{\mathrm{val}})\\ \text{paired samples}}}^{N} \sum_{i=1}^{M} \,R^2\!\bigl(\mathrm{marker}_i \mid B\bigr)$

        Where:
        - $N$ is the number of paired samples, where x_{\mathrm{int}} is the replicate that has been batch-corrected and x_{\mathrm{val}} is replicate used for validation. Paired samples belong to different batches.
        - $M$ is the number of markers
        - $B$ is the batch covariate

        A higher value of $\overline{R^2_B}_{global}$ indicates that the batch variable explains more of the variance in the data, which indicates a higher level of batch effects. |


      references:
        bibtex:
          - |
            @book{draper1998applied,
            title={Applied regression analysis},
            author={Draper, Norman R and Smith, Harry},
            publisher={John Wiley \& Sons}
            }
      links:
        # URL to the documentation for this metric (required).
        documentation: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
        # URL to the code repository for this metric (required).
        repository: https://github.com/scikit-learn/scikit-learn
      # The minimum possible value for this metric (required)
      min: -0.001
      # The maximum possible value for this metric (required)
      max: 1
      # Whether a higher value represents a 'better' solution (required)
      maximize: false


    - name: average_batch_r2_ct
      # A relatively short label, used when rendering visualisarions (required)
      label: Average Batch R-squared Cell Type
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "The average batch R-squared Cell Type quantifies, on average, how strongly the batch variable B explains the variance in the data (by taking into account cell type effect)."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        First, a simple linear model `sklearn.linear_model.LinearRegression` is fitted for each paired sample, marker and cell type to determine the fraction of variance (R^2) explained by the batch covariate B. |
        The average batch R_squared is then computed as the average of the $R^2$ values across all paired samples, markers and cell types. |
        As a result, $\overline{R^2_B}_{cell\ type}$ quantifies how much of the total variability in the data is driven by batch effects. Consequently, lower values are desirable. |

        $\overline{R^2_B}_{cell\ type} = \frac{1}{N*C*M}\sum_{\substack{(x_{\mathrm{int}},\,x_{\mathrm{val}})\\ \text{paired samples}}}^{N} \sum_{j=1}^{C} \sum_{i=1}^{M}\,R^2\!\bigl(\mathrm{marker}_i \mid B\bigr)$

        Where:
        - $N$ is the number of paired samples, where x_{\mathrm{int}} is the replicate that has been batch-corrected and x_{\mathrm{val}} is replicate used for validation. Paired samples belong to different batches.
        - $C$ is the number of cell types
        - $M$ is the number of markers
        - $B$ is the batch covariate

        The $\overline{RË†2_B}_{global}$ is a variation of the latter metric, where the average is computed across paired samples and markers only, without taking into account the cell types. |

        A higher value of $\overline{R^2_B}_{global}$ or $\overline{R^2_B}_{cell\ type}$ indicates that the batch variable explains more of the variance in the data, which indicates a higher level of batch effects. |
        
        A good performance on $\overline{R^2_B}_{global}$ but not on $\overline{R^2_B}_{cell\ type}$ might indicate that the batch effect correction is discarding cell type specific batch effects. |
      
      references:
        bibtex:
          - |
            @book{draper1998applied,
            title={Applied regression analysis},
            author={Draper, Norman R and Smith, Harry},
            publisher={John Wiley \& Sons}
            }
      links:
        # URL to the documentation for this metric (required).
        documentation: https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LinearRegression.html
        # URL to the code repository for this metric (required).
        repository: https://github.com/scikit-learn/scikit-learn
      # The minimum possible value for this metric (required)
      min: -0.001
      # The maximum possible value for this metric (required)
      max: 1
      # Whether a higher value represents a 'better' solution (required)
      maximize: false


# Component-specific parameters (optional)
# arguments:
#   - name: "--n_neighbors"
#     type: "integer"
#     default: 5
#     description: Number of neighbors to use.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: python_script
    path: script.py
  - path: helper.py
  - path: /src/utils/helper_functions.py


engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_python:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    # setup:
    #   - type: python
    #     packages: numpy<2

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
