import anndata as ad
import sys

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_validation': 'resources_test/.../validation.h5ad',
  'input_unintegrated': 'resources_test/.../unintegrated.h5ad',
  'input_integrated': 'resources_test/.../integrated.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'average_batch_r2'
}
## VIASH END

sys.path.append(meta["resources_dir"])
from helper import concat_paired_samples, fit_r2, batch_r2
from helper_functions import get_obs_var_for_integrated, subset_nocontrols, subset_markers_tocorrect, remove_unlabelled

print('Reading input files', flush=True)
input_validation = ad.read_h5ad(par['input_validation'])
input_unintegrated = ad.read_h5ad(par['input_unintegrated'])
input_integrated = ad.read_h5ad(par['input_integrated'])

print(input_validation, input_unintegrated, input_integrated)

print('Compute metrics', flush=True)

# metric_ids and metric_values can have length > 1
# but should be of equal length
uns_metric_ids = [ 'average_batch_r2' ]
uns_metric_values = [ 0.5 ]

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
    uns={
    'dataset_id': input_integrated.uns['dataset_id'],
    'method_id': input_integrated.uns['method_id'],
    'metric_ids': uns_metric_ids,
    'metric_values': uns_metric_values
  }
)
output.write_h5ad(par['output'], compression='gzip')
