import anndata as ad

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input_unintegrated': 'resources_test/.../unintegrated.h5ad',
  'input_validation': 'resources_test/.../validation.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'no_integration'
}
## VIASH END

print('Reading input files', flush=True)
adata = ad.read_h5ad(par['input_unintegrated'])

integrated = adata.layers[ 'preprocessed'] 

print("Write output AnnData to file", flush=True)
output = ad.AnnData(
    obs=adata.obs[[]],
    var=adata.var[[]],
    layers={"integrated": integrated},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": meta["name"],
        "parameters": {},
    },
)

output.write_h5ad(par['output'], compression='gzip')
