name: process_datasets
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        __merge__: /src/api/file_common_dataset.yaml
        direction: input
        required: true
  - name: Outputs
    arguments:
      - name: "--output_unintegrated"
        __merge__: /src/api/file_unintegrated.yaml
        direction: output
        required: true
      - name: "--output_censored_split1"
        __merge__: /src/api/file_censored_split1.yaml
        direction: output
        required: true
      - name: "--output_censored_split2"
        __merge__: /src/api/file_censored_split2.yaml
        direction: output
        required: true

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: validation/check_dataset_with_schema
    repository: op
  - name: data_processors/process_dataset

runners:
  - type: nextflow
