name: process_datasets
namespace: workflows

argument_groups:
  - name: Inputs
    arguments:
      - name: "--input"
        __merge__: /src/api/file_common_dataset.yaml
        direction: input
        required: true
  - name: Outputs
    arguments:
      - name: "--output_unintegrated_censored"
        __merge__: /src/api/file_unintegrated_censored.yaml
        direction: output
        required: true
      - name: "--output_unintegrated"
        __merge__: /src/api/file_unintegrated.yaml
        direction: output
        required: true
      - name: "--output_validation"
        __merge__: /src/api/file_validation.yaml
        direction: output
        required: true

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - path: /common/nextflow_helpers/helper.nf

dependencies:
  - name: schema/verify_data_structure
    repository: core
  - name: data_processors/process_dataset

runners:
  - type: nextflow
