import anndata as ad
import scanpy as sc

## VIASH START
# Note: this section is auto-generated by viash at runtime. To edit it, make changes
# in config.vsh.yaml and then run `viash config inject config.vsh.yaml`.
par = {
  'input': 'resources_test/task_cyto_batch_integration/starter_file/unintegrated_censored.h5ad',
  'output': 'output.h5ad'
}
meta = {
  'name': 'combat'
}
## VIASH END

print('Reading input files', flush=True)
adata = ad.read_h5ad(par["input"])

print('Preprocess data', flush=True)
markers_to_correct = adata.var[adata.var["to_correct"]].index.to_numpy()
adata_to_correct = adata[:,markers_to_correct].copy()
adata_to_correct.X = adata_to_correct.layers['preprocessed']

print('Train model', flush=True)
integrated_data = sc.pp.combat(adata_to_correct, key='batch',inplace=False)

print("Write output AnnData to file", flush=True)
out_data = ad.AnnData(
    obs=adata_to_correct.obs[[]],
    var=adata_to_correct.var[[]],
    layers={"integrated": integrated_data},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": 'combat',
        "parameters": {},
    },
)


out_data.write_h5ad(par['output'], compression='gzip')
