name: run_benchmark
namespace: workflows
argument_groups:
  - name: Inputs
    arguments:
      - name: "--input_unintegrated_censored"
        __merge__: /src/api/file_unintegrated_censored.yaml
        type: file
        direction: input
        required: true
      - name: "--input_unintegrated"
        __merge__: /src/api/file_unintegrated.yaml
        type: file
        direction: input
        required: true
      - name: "--input_validation"
        __merge__: /src/api/file_validation.yaml
        type: file
        direction: input
        required: true
  - name: Outputs
    arguments:
      - name: "--output_scores"
        type: file
        required: true
        direction: output
        description: A yaml file containing the scores of each of the methods
        default: score_uns.yaml
      - name: "--output_method_configs"
        type: file
        required: true
        direction: output
        default: method_configs.yaml
      - name: "--output_metric_configs"
        type: file
        required: true
        direction: output
        default: metric_configs.yaml
      - name: "--output_dataset_info"
        type: file
        required: true
        direction: output
        default: dataset_uns.yaml
      - name: "--output_task_info"
        type: file
        required: true
        direction: output
        default: task_info.yaml
  - name: Methods
    arguments:
      - name: "--method_ids"
        type: string
        multiple: true
        description: A list of method ids to run. If not specified, all methods will be run.

resources:
  - type: nextflow_script
    path: main.nf
    entrypoint: run_wf
  - type: file
    path: /_viash.yaml

dependencies:
  - name: utils/extract_uns_metadata
    repository: op
  - name: control_methods/shuffle_integration
  - name: control_methods/shuffle_integration_by_batch
  - name: control_methods/shuffle_integration_by_cell_type
  - name: control_methods/no_integration
  - name: control_methods/perfect_integration_horizontal
  - name: control_methods/perfect_integration_vertical
  - name: methods/harmonypy
  - name: methods/limma_remove_batch_effect
  - name: methods/combat
  - name: methods/cycombine_nocontrols
  - name: methods/gaussnorm
  - name: methods/cytonorm_controls
  - name: metrics/emd
  - name: metrics/n_inconsistent_peaks
  - name: metrics/average_batch_r2
  - name: metrics/flowsom_mapping_similarity

runners:
  - type: nextflow
