__merge__: ../../api/comp_metric.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: cms

# Metadata for your component
info:
  metrics:
      # A unique identifier for your metric (required).
      # Can contain only lowercase letters or underscores.
    - name: cms
      # A relatively short label, used when rendering visualisarions (required)
      label: Cell Mixing Score
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "Cellspecific Mixing Score (cms) quantifies batch effects at the cell level by computing batch-specific distance distributions towards k-nearest neighbouring cells."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        The cellspecific mixing score cms tests for each cell the hypothesis that batch-specific distance 
        distributions towards it's k-nearest neighbouring (knn) cells are derived from the same unspecified 
        underlying distribution using the Anderson-Darling test. The test considers differences in the number of cells 
        from each batch, making the cms a robust metric when evaluating batch effects in datasets with unbalanced batch sizes.
        This implementation uses k = 50 knn cells and the first 10 principal components for distance computations.

        The cms for each cell can be interpreted as a P-value, that is, the probability of observing deviations 
        in the batch specific distance distributions by chance (assuming they are all derived from the same distribution).
        Therefore, for a given cell:
        - A low cms score indicates that the batch-specific distance distributions towards its knn cells are significantly different, 
          suggesting that the cell is influenced by batch effects.
        - A high cms score indicates that the batch-specific distance distributions towards its knn cells are similar, 
          suggesting that the cell is not influenced by batch effects.
        

        To characterize the overall batch mixing in a dataset, we use the medcouple statistic on the distribution of cms scores.
        The medcouple is a robust measure of skewness, which is less sensitive to outliers than the traditional skewness measure.
        The medcouple statistic returns values between -1 and 1, where:
        - A value close to -1 indicates a pronounced left-skewed distribution, reflecting abundance of cells with high cms scores
        - A value close to 1 indicates a pronounced right-skewed distribution, reflecting abundance of cells with low cms scores
        - A value around 0 indicates a symmetrical distribution of cms scores

        It has been empirically observed that a uniform (thus, symmetrical) distribution of cms scores across cells in a dataset is indicative of good mixing
        (e.g. via random shuffling of batch labels in a dataset). Therefore, a medcouple around 0 or lower is considered a good mixing score.

      references:
        doi: 
          - 10.26508/lsa.202001004
        bibtex:
          - |
            @article{lutge2021cellmixs,
              title={CellMixS: quantifying and visualizing batch effects in single-cell RNA-seq data},
              author={L{\"u}tge, Almut and Zyprych-Walczak, Joanna and Kunzmann, Urszula Brykczynska and Crowell, Helena L and Calini, Daniela and Malhotra, Dheeraj and Soneson, Charlotte and Robinson, Mark D},
              journal={Life science alliance},
              volume={4},
              number={6},
              year={2021},
              publisher={Life Science Alliance}
            }
          - |
            @article{brys2004robust,
              title={A robust measure of skewness},
              author={Brys, Guy and Hubert, Mia and Struyf, Anja},
              journal={Journal of Computational and Graphical Statistics},
              volume={13},
              number={4},
              pages={996--1017},
              year={2004},
              publisher={Taylor \& Francis}
            }

      links:
        # URL to the documentation for this metric (required).
        documentation: https://bioconductor.org/packages/release/bioc/html/CellMixS.html
        # URL to the code repository for this metric (required).
        repository: https://github.com/almutlue/CellMixS
      # The minimum possible value for this metric (required)
      min: -1
      # The maximum possible value for this metric (required)
      max: 1
      # Whether a higher value represents a 'better' solution (required)
      maximize: false

# Component-specific parameters (optional)
arguments:
  - name: "--n_neighbors"
    type: "integer"
    default: 50
    description: Number of k-nearest neighbours (knn) to use when computing cms scores.
  - name: "--n_dim"
    type: "integer"
    default: 10
    description: Number of principal components to use when computing cms scores.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: r_script
    path: script.R

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_r:1.0.0
    setup:
      - type: r
        packages: [robustbase, hdf5r]
        bioc: [CellMixS, SingleCellExperiment, Biocparallel]
        github: [scverse/anndataR]

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
