requireNamespace("anndataR", quietly = TRUE)
requireNamespace("CellMixS", quietly = TRUE)
requireNamespace("BiocParallel", quietly = TRUE)
requireNamespace("robustbase", quietly = TRUE)
requireNamespace("parallel", quietly = TRUE)
requireNamespace("SingleCellExperiment", quietly = TRUE)

## VIASH START
# The following code has been auto-generated by Viash.
# treat warnings as errors

par <- list(
    input_unintegrated = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    input_integrated_left = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_left.h5ad",
    input_integrated_right = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_right.h5ad",
    output = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/score_cms.h5ad",
    n_neighbors = as.integer("50"),
    n_dim = as.integer("10")
)
meta <- list(
    name = "cms",
    resources_dir = "src/utils"
)
## VIASH END

source(paste0(meta$resources_dir, "/helper_functions.R"))


cat("Reading input files\n")
unintegrated <- anndataR::read_h5ad(par[["input_unintegrated"]])
integrated_left <- anndataR::read_h5ad(par[["input_integrated_left"]])
integrated_right <- anndataR::read_h5ad(par[["input_integrated_right"]])

cat("Fetching some metadata from unintegrated\n")
integrated_left <- get_obs_var_for_integrated(
    i_adata = integrated_left,
    u_adata = unintegrated
)
integrated_right <- get_obs_var_for_integrated(
    i_adata = integrated_right,
    u_adata = unintegrated
)

# Fetch batch annotations from unintegrated
# batch_key <- input_unintegrated$obs$batch

# Get markers to correct
markers_to_correct <- unintegrated$var_names[unintegrated$var$to_correct]

cat("Converting to SingleCellExperiment object\n")

# Convert to SingleCellExperiment
integrated_left_sce <- integrated_left$as_SingleCellExperiment()
integrated_left_sce <- integrated_left_sce[markers_to_correct, ]

integrated_right_sce <- integrated_right$as_SingleCellExperiment()
integrated_right_sce <- integrated_right_sce[markers_to_correct, ]

cores_to_use <- ceiling(parallel::detectCores() / 2)

cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 1\n"))

integrated_left_sce <- CellMixS::cms(
    integrated_left_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = BiocParallel::MulticoreParam(
        workers = cores_to_use
    )
)

cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 2\n"))

integrated_right_sce <- CellMixS::cms(
    integrated_right_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = BiocParallel::MulticoreParam(
        workers = cores_to_use
    )
)

cat("Compute Medcouple statistic\n")

cms_distr_left <- SingleCellExperiment::colData(integrated_left_sce)[, "cms"]
cms_distr_right <- SingleCellExperiment::colData(integrated_right_sce)[, "cms"]

cms_mc_left <- robustbase::mc(cms_distr_left)
cms_mc_right <- robustbase::mc(cms_distr_right)

cms_mc_mean <- mean(c(cms_mc_left, cms_mc_right))

cat("Write output AnnData to file\n")
output <- anndataR::AnnData(
    shape = c(0L, 0L),
    uns = list(
        dataset_id = integrated_left$uns$dataset_id,
        method_id = integrated_left$uns$method_id,
        metric_ids = meta$name,
        metric_values = cms_mc_mean,
        cms_parameters = list(
            n_neighbors = par[["n_neighbors"]],
            n_dim = par[["n_dim"]]
        ),
        cms_medcouple_score = list(
            left = cms_mc_left,
            right = cms_mc_right
        ),
        cms_distribution = list(
            left = cms_distr_left,
            right = cms_distr_right
        )
    )
)

output$write_h5ad(par[["output"]], compression = "gzip", mode = "w")
