requireNamespace("anndataR", quietly = TRUE)
requireNamespace("CellMixS", quietly = TRUE)
requireNamespace("BiocParallel", quietly = TRUE)
requireNamespace("robustbase", quietly = TRUE)
requireNamespace("parallel", quietly = TRUE)
requireNamespace("SingleCellExperiment", quietly = TRUE)

## VIASH START
# The following code has been auto-generated by Viash.
# treat warnings as errors

par <- list(
    input_unintegrated = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    input_integrated_split1 = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_split1.h5ad",
    input_integrated_split2 = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_split2.h5ad",
    output = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/score_cms.h5ad",
    n_neighbors = as.integer("50"),
    n_dim = as.integer("10")
)
meta <- list(
    name = "cms",
    resources_dir = "src/utils",
    cpus = NULL
)
## VIASH END

cores_to_use <- meta$cpus
if (is.null(cores_to_use)) {
    cores_to_use <- min(5, parallel::detectCores() - 2)
}

source(paste0(meta$resources_dir, "/helper_functions.R"))


cat("Reading input files\n")
unintegrated <- anndataR::read_h5ad(par[["input_unintegrated"]])
integrated_split1 <- anndataR::read_h5ad(par[["input_integrated_split1"]])
integrated_split2 <- anndataR::read_h5ad(par[["input_integrated_split2"]])

cat("Fetching some metadata from unintegrated\n")
integrated_split1 <- get_obs_var_for_integrated(
    i_adata = integrated_split1,
    u_adata = unintegrated
)
integrated_split2 <- get_obs_var_for_integrated(
    i_adata = integrated_split2,
    u_adata = unintegrated
)

# Fetch batch annotations from unintegrated
# batch_key <- input_unintegrated$obs$batch

# Get markers to correct
markers_to_correct <- unintegrated$var_names[unintegrated$var$to_correct]

cat("Converting to SingleCellExperiment object\n")

# Convert to SingleCellExperiment
integrated_split1_sce <- integrated_split1$as_SingleCellExperiment()
integrated_split1_sce <- integrated_split1_sce[markers_to_correct, ]

integrated_split2_sce <- integrated_split2$as_SingleCellExperiment()
integrated_split2_sce <- integrated_split2_sce[markers_to_correct, ]

# cores_to_use <- 5
bpparam <- BiocParallel::MulticoreParam(
    workers = cores_to_use
)
cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 1\n"))

integrated_split1_sce <- CellMixS::cms(
    integrated_split1_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = bpparam
)

cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 2\n"))

integrated_split2_sce <- CellMixS::cms(
    integrated_split2_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = bpparam
)

cat("Compute Medcouple statistic\n")

cms_distr_split1 <- SingleCellExperiment::colData(integrated_split1_sce)[, "cms"]
cms_distr_split2 <- SingleCellExperiment::colData(integrated_split2_sce)[, "cms"]

cms_mc_split1 <- robustbase::mc(cms_distr_split1)
cms_mc_split2 <- robustbase::mc(cms_distr_split2)

cms_mc_mean <- mean(c(cms_mc_split1, cms_mc_split2))

cat("Write output AnnData to file\n")
output <- anndataR::AnnData(
    shape = c(0L, 0L),
    uns = list(
        dataset_id = integrated_split1$uns$dataset_id,
        method_id = integrated_split1$uns$method_id,
        metric_ids = meta$name,
        metric_values = cms_mc_mean,
        cms_parameters = list(
            n_neighbors = par[["n_neighbors"]],
            n_dim = par[["n_dim"]]
        ),
        cms_medcouple_score = list(
            left = cms_mc_split1,
            right = cms_mc_split2
        ),
        cms_distribution = list(
            left = cms_distr_split1,
            right = cms_distr_split2
        )
    )
)

output$write_h5ad(par[["output"]], compression = "gzip", mode = "w")
