requireNamespace("anndataR", quietly = TRUE)
requireNamespace("CellMixS", quietly = TRUE)
requireNamespace("BiocParallel", quietly = TRUE)
requireNamespace("robustbase", quietly = TRUE)
requireNamespace("parallel", quietly = TRUE)
requireNamespace("SingleCellExperiment", quietly = TRUE)

## VIASH START
# The following code has been auto-generated by Viash.
# treat warnings as errors

par <- list(
    input_unintegrated = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    input_integrated_split1 = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_split1.h5ad",
    input_integrated_split2 = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_split2.h5ad",
    output = "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/score_cms.h5ad",
    n_neighbors = as.integer("50"),
    n_dim = as.integer("10")
)
meta <- list(
    name = "cms",
    resources_dir = "src/utils",
    cpus = NULL
)
## VIASH END

cores_to_use <- meta$cpus
if (is.null(cores_to_use)) {
    cores_to_use <- min(5, parallel::detectCores() - 2)
}
bpparam <- BiocParallel::MulticoreParam(
    workers = cores_to_use
)

source(paste0(meta$resources_dir, "/helper_functions.R"))


cat("Reading input files\n")
unintegrated <- anndataR::read_h5ad(par[["input_unintegrated"]])
integrated_split1 <- anndataR::read_h5ad(par[["input_integrated_split1"]])
integrated_split2 <- anndataR::read_h5ad(par[["input_integrated_split2"]])

cat("Fetching metadata from unintegrated\n")
integrated_split1 <- get_obs_var_for_integrated(
    i_adata = integrated_split1,
    u_adata = unintegrated
)
integrated_split2 <- get_obs_var_for_integrated(
    i_adata = integrated_split2,
    u_adata = unintegrated
)

# Get markers to correct
markers_to_correct <- unintegrated$var_names[unintegrated$var$to_correct]

cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 1\n"))

cms_distr_split1 <- list()
medcouples_split1 <- list()

integrated_subset <- subset_by_celltype(
    integrated_split1,
    frac = 0.6,
    seed = 1
)

cat("Transforming to SingleCellExperiment and subsetting markers\n")
integrated_subset_sce <- integrated_subset$as_SingleCellExperiment()
integrated_subset_sce <- integrated_subset_sce[markers_to_correct, ]
cat("Computing Cell Mixing Scores\n")
integrated_subset_sce <- CellMixS::cms(
    integrated_subset_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = bpparam
)
distr <- SingleCellExperiment::colData(integrated_subset_sce)[, "cms"]
cms_distr_split1[["split1"]] <- distr
medcouples_split1[["split1"]] <- robustbase::mc(distr)

cat(paste("Compute Cell Mixing Score using", cores_to_use, "cores for split 2\n"), flush = TRUE)

cms_distr_split2 <- list()
medcouples_split2 <- list()

integrated_subset <- subset_by_celltype(
    integrated_split2,
    frac = 0.6,
    seed = 1
)
cat("Transforming to SingleCellExperiment and subsetting markers\n")
integrated_subset_sce <- integrated_subset$as_SingleCellExperiment()
integrated_subset_sce <- integrated_subset_sce[markers_to_correct, ]
cat("Computing Cell Mixing Scores\n")
integrated_subset_sce <- CellMixS::cms(
    integrated_subset_sce,
    group = "batch",
    assay_name = "integrated",
    k = par[["n_neighbors"]],
    n_dim = par[["n_dim"]],
    BPPARAM = bpparam
)
distr <- SingleCellExperiment::colData(integrated_subset_sce)[, "cms"]
cms_distr_split2[["split2"]] <- distr
medcouples_split2[["split2"]] <- robustbase::mc(distr)


cat("Aggregate scores\n", flush = TRUE)
#concat named lists
cms_distr_list <- c(cms_distr_split1, cms_distr_split2)
medcouples_list <- c(medcouples_split1, medcouples_split2)
# Compute mean medcouple
mean_medcouple_cms <- mean(unlist(medcouples_list))

cat("Write output AnnData to file\n", flush = TRUE)
output <- anndataR::AnnData(
    shape = c(0L, 0L),
    uns = list(
        dataset_id = integrated_split1$uns$dataset_id,
        method_id = integrated_split1$uns$method_id,
        metric_ids = meta$name,
        metric_values = mean_medcouple_cms,
        cms_parameters = list(
            n_neighbors = par[["n_neighbors"]],
            n_dim = par[["n_dim"]]
        ),
        list_medcouples = medcouples_list,
        cms_distributions = cms_distr_list
    )
)

output$write_h5ad(par[["output"]], compression = "gzip", mode = "w")
