# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_metric.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: emd

# Metadata for your component
info:
  metrics:
      # A unique identifier for your metric (required).
      # Can contain only lowercase letters or underscores.
    - name: emd
      # A relatively short label, used when rendering visualisarions (required)
      label: EMD
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "Earth Mover Distance to compute differences in distribution of marker expressions."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        Earth Mover Distance (EMD) is a metric designed for comparing two distributions.
        It is also known as the Wasserstein metric.
      references:
        doi: 
          - 10.1023/A:1026543900054
      links:
        # URL to the documentation for this metric (required).
        documentation: https://cytonormpy.readthedocs.io/en/latest/generated/cytonormpy.emd_comparison_from_anndata.html
        # URL to the code repository for this metric (required).
        repository: https://github.com/TarikExner/CytoNormPy
      # The minimum possible value for this metric (required)
      min: 0
      # The maximum possible value for this metric (required)
      max: .inf
      # Whether a higher value represents a 'better' solution (required)
      maximize: false
  # Keep this just for future metrics' reference if required
  # Note: need this if we have component specific argument with no default.
  # When running the actual command, either split the sample name by ;
  # so Tube1_Batch1_WT;Tube1_Batch2_WT
  # or repeat the flag twice. So --samples_to_compare Tube1_Batch1_WT
  # --samples_to_compare Tube1_Batch2_WT
  # test_setup:
  #   starter_file:
  #     samples_to_compare: 
  #       - Tube1_Batch1_WT
  #       - Tube1_Batch2_WT
      
# Component-specific parameters (optional)
# Keep for now for future metrics' reference if required
# arguments:
#   - name: "--samples_to_compare"
#     type: "string"
#     description: 2 samples to compare.
#     required: true
#     multiple: true

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: python_script
    path: script.py

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_python:1.0.0
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: python
        packages: [anndata, numpy, pandas]
        github: [TarikExner/CytoNormPy]

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]