# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_metric.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: bras



# Metadata for your component
info:
  metrics:
      # A unique identifier for your metric (required).
      # Can contain only lowercase letters or underscores.
    - name: bras
      # A relatively short label, used when rendering visualisarions (required)
      label: Bras
      # A one sentence summary of how this metric works (required). Used when 
      # rendering summary tables.
      summary: "Batch removal adapted silhouette (BRAS)."
      # A multi-line description of how this component works (required). Used
      # when rendering reference documentation.
      description: |
        BRAS evaluates batch effect removal with respect to batch ids within each label (cell type annotations derived from manual gating),
        using a modified silhouette score that accounts for nested batch effects.
        Unlike standard silhouette, BRAS computes between-cluster distances using the between_cluster_distances method rather than nearest-cluster approach. 
        The implementation is based on the scib-metrics package. The final bras score is the average of the bras scores for both data splits.
        Cosine similarity is used as a distance measure.
        A higher scores indicates better batch mixing.
      references:
        doi: 
          - 10.1101/2025.01.21.634098
        bibtex:
          - |
            @article{rautenstrauch2025metrics,
              title={Metrics Matter: Why We Need to Stop Using Silhouette in Single-Cell Benchmarking},
              author={Rautenstrauch, Pia and Ohler, Uwe},
              journal={bioRxiv},
              pages={2025--01},
              year={2025},
              publisher={Cold Spring Harbor Laboratory}
            }
      links:
        # URL to the documentation for this metric (required).
        documentation: https://scib-metrics.readthedocs.io/en/stable/generated/scib_metrics.bras.html
        # URL to the code repository for this metric (required).
        repository: https://github.com/YosefLab/scib-metrics/blob/main/src/scib_metrics/metrics/_silhouette.py
      # The minimum possible value for this metric (required)
      min: 0
      # The maximum possible value for this metric (required)
      max: 1
      # Whether a higher value represents a 'better' solution (required)
      maximize: true

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: python_script
    path: script.py
  - path: /src/utils/helper_functions.py


engines:
  # Specifications for the Docker image for this component.
  # testing gpu jax version
  - type: docker
    image: nvidia/cuda:13.0.1-cudnn-devel-ubuntu24.04
    setup:
      - type: apt
        packages:
          - python3-pip
          - procps
          - git
      - type: python
        packages:
          - jax[cuda_13]
          - anndata~=0.11.0
          - scanpy~=1.11.0
          - scib-metrics~=0.5.7
          - pyyaml
          - requests
          - jsonschema
          - scikit-learn
        github:
          - openproblems-bio/core#subdirectory=packages/python/openproblems
  # - type: docker
  #   image: python:3.11
  #   setup:
  #     - type: apt
  #       packages:
  #         - procps
  #     - type: python
  #       packages:
  #         - jax~=0.6.2
  #         - jaxlib~=0.6.2
  #         - anndata~=0.11.0
  #         - scanpy~=1.11.0
  #         - scib-metrics~=0.5.6
  #         - pyyaml
  #         - requests
  #         - jsonschema
  #       github:
  #         - "openproblems-bio/core#subdirectory=packages/python/openproblems"

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,lowcpu,gpu]
