import anndata as ad

## VIASH START
# The following code has been auto-generated by Viash.
par = {
    "input_unintegrated": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    "output_integrated_left": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_left.h5ad",
    "output_integrated_right": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/integrated_right.h5ad",
}
meta = {"name": "perfect_integration"}

## VIASH END

print("Reading input files", flush=True)
adata = ad.read_h5ad(par["input_unintegrated"])

print("Extracting and splitting unintegrated data", flush=True)

# split 1
adata_left = adata[(adata.obs.is_control > 0) | (adata.obs.batch == 1)]
integrated_left = adata_left.layers["preprocessed"]

# split 2 == split 1 in this case

print("Write output AnnData to file", flush=True)
# split 1
output_left = ad.AnnData(
    obs=adata_left.obs[[]],
    var=adata_left.var[[]],
    layers={"integrated": integrated_left},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": meta["name"],
        "parameters": {},
    },
)
# split 2
output_right = ad.AnnData(
    obs=adata_left.obs[[]],
    var=adata_left.var[[]],
    layers={"integrated": integrated_left},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": meta["name"],
        "parameters": {},
    },
)

output_left.write_h5ad(par["output_integrated_left"], compression="gzip")
output_right.write_h5ad(par["output_integrated_right"], compression="gzip")
