import anndata as ad

## VIASH START
# The following code has been auto-generated by Viash.
par = {
    "input_unintegrated": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/unintegrated.h5ad",
    "output_integrated_split1": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/perfect_integrated_split1.h5ad",
    "output_integrated_split2": "resources_test/task_cyto_batch_integration/mouse_spleen_flow_cytometry_subset/perfect_integrated_split2.h5ad",
}
meta = {"name": "perfect_integration"}

## VIASH END

print("Reading input files", flush=True)
adata = ad.read_h5ad(par["input_unintegrated"])

# make sure batch is string so we don't run into issues later on when subsetting
# also make sure is_control is numeric
adata.obs["batch"] = adata.obs["batch"].astype("str")
adata.obs["is_control"] = adata.obs["is_control"].astype(int)

print("Extracting and splitting unintegrated data", flush=True)

# split 1
# reminder: is_control > 0 will include control samples.
adata_split1 = adata[(adata.obs.is_control > 0) | (adata.obs.batch == "1")]
integrated_split1 = adata_split1.layers["preprocessed"]

# split 2 == split 1 in this case

print(
    "Sanity check: verifying perfect integration have both control and non-control samples",
    flush=True,
)
# Check that we have both control and non-control cells
n_control = (adata_split1.obs.is_control > 0).sum()
n_non_control = (adata_split1.obs.is_control == 0).sum()

assert n_non_control > 0, (
    f"Split 1 should contain cells from non-control samples, but found {n_non_control} cells!"
)
assert n_control > 0, (
    f"Split 1 should contain cells from control samples, but found {n_control} cells!"
)


print("Write output AnnData to file", flush=True)
# split 1
output_split1 = ad.AnnData(
    obs=adata_split1.obs[[]],
    var=adata_split1.var[[]],
    layers={"integrated": integrated_split1},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": meta["name"],
        "parameters": {},
    },
)
# split 2
output_split2 = ad.AnnData(
    obs=adata_split1.obs[[]],
    var=adata_split1.var[[]],
    layers={"integrated": integrated_split1},
    uns={
        "dataset_id": adata.uns["dataset_id"],
        "method_id": meta["name"],
        "parameters": {},
    },
)

output_split1.write_h5ad(par["output_integrated_split1"], compression="gzip")
output_split2.write_h5ad(par["output_integrated_split2"], compression="gzip")
