# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: rpca_to_goal
# A relatively short label, used when rendering visualisations (required)
label: Seurat RPCA To Goal

# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "Integrates query datasets into a reference (goal) batch using mutual nearest neighbors identified via reciprocal PCA."

# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  This method performs batch integration by projecting each query dataset into the PCA space of a reference (goal) batch, and identifying anchors 
  (corresponding biological states) using reciprocal PCA (RPCA). 
  RPCA identifies mutual nearest neighbors between the reference and query datasets in their shared low-dimensional space, which are used to align 
  and integrate the query into the reference. This is a supervised integration approach, preserving biological variation while correcting 
  for batch effects, and is particularly suitable when the reference batch is well-annotated or biologically representative.

references:
  doi: 
    - 10.1016/j.cell.2021.04.048
  bibtex:
    - |
      @article{hao2021integrated,
        title={Integrated analysis of multimodal single-cell data},
        author={Hao, Yuhan and Hao, Stephanie and Andersen-Nissen, Erica and Mauck, William M and Zheng, Shiwei and Butler, Andrew and Lee, Madison J and Wilk, Aaron J and Darby, Charlotte and Zager, Michael and others},
        journal={Cell},
        volume={184},
        number={13},
        pages={3573--3587},
        year={2021},
        publisher={Elsevier}
      }

links:
  # URL to the documentation for this method (required).
  documentation: https://satijalab.org/seurat/articles/integration_rpca.html
  # URL to the code repository for this method (required).
  repository: https://github.com/satijalab/seurat



# Component-specific parameters (optional)
# arguments:
#   - name: "--n_neighbors"
#     type: "integer"
#     default: 5
#     description: Number of neighbors to use.

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: r_script
    path: script.R
  # Additional resources your script needs (optional)
  # - type: file
  #   path: weights.pt

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_r:1.0.0
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    # setup:
    #   - type: r
    #     packages: tibble

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
