# The API specifies which type of component this is.
# It contains specifications for:
#   - The input/output files
#   - Common parameters
#   - A unit test
__merge__: ../../api/comp_method.yaml

# A unique identifier for your component (required).
# Can contain only lowercase letters or underscores.
name: rpca_to_goal
# A relatively short label, used when rendering visualisations (required)
label: Seurat RPCA (to-goal)

# A one sentence summary of how this method works (required). Used when 
# rendering summary tables.
summary: "Batch integrate data to a goal batch using mutual nearest neighbors identified via Seurat reciprocal PCA."

# A multi-line description of how this component works (required). Used
# when rendering reference documentation.
description: |
  Seurat RPCA performs batch integration by projecting each query dataset into the PCA space 
  of a goal batch, and identifying anchors using reciprocal PCA (RPCA). 
  RPCA identifies mutual nearest neighbors between the goal batch and the remaining batches 
  in their shared low-dimensional space (PCA), which are used to align 
  and integrate the batches into the goal batch. 

  We ran Seurat RPCA implemented in Seurat v4.4.0, available on their github.
  This is because subsequent version (>= v5) does not support getting corrected
  count matrix, only corrected PC space.
  See: https://github.com/satijalab/seurat/issues/8551.

  We varied the number of PCs and nearest neighbours considered when running RPCA.

references:
  doi: 
    - 10.1016/j.cell.2021.04.048
  bibtex:
    - |
      @article{hao2021integrated,
        title={Integrated analysis of multimodal single-cell data},
        author={Hao, Yuhan and Hao, Stephanie and Andersen-Nissen, Erica and Mauck, William M and Zheng, Shiwei and Butler, Andrew and Lee, Madison J and Wilk, Aaron J and Darby, Charlotte and Zager, Michael and others},
        journal={Cell},
        volume={184},
        number={13},
        pages={3573--3587},
        year={2021},
        publisher={Elsevier}
      }

links:
  # URL to the documentation for this method (required).
  documentation: https://satijalab.org/seurat/articles/integration_rpca.html
  # URL to the code repository for this method (required).
  repository: https://github.com/satijalab/seurat

argument_groups:
  - name: Parameters
    arguments:
      - type: integer
        name: --npcs
        info:
          optimize:
            type: linear
            lower: 10
            upper: 20
        default: 10
        description: The number of principal component (PC) dimensions to use when computing anchors between batches.
      - type: integer
        name: --n_neighbours
        info:
          optimize:
            type: linear
            lower: 5
            upper: 50
        default: 5
        description: The number of mutual nearest neighbors that are used when identifying anchors between batches

# Resources required to run the component
resources:
  # The script of your component (required)
  - type: r_script
    path: script.R

engines:
  # Specifications for the Docker image for this component.
  - type: docker
    image: openproblems/base_r:1
    # Add custom dependencies here (optional). For more information, see
    # https://viash.io/reference/config/engines/docker/#setup .
    setup:
      - type: r
        url: [
          https://cran.r-project.org/src/contrib/Archive/Seurat/Seurat_4.4.0.tar.gz,
          https://cran.r-project.org/src/contrib/Archive/SeuratObject/SeuratObject_4.1.4.tar.gz
        ]

runners:
  # This platform allows running the component natively
  - type: executable
  # Allows turning the component into a Nextflow module / pipeline.
  - type: nextflow
    directives:
      label: [midtime,midmem,midcpu]
